package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"

	"github.com/GigaDesk/eardrum-postgres/product"
	"github.com/GigaDesk/eardrum-server/auth"
	"github.com/GigaDesk/eardrum-server/graph/model"
	"github.com/GigaDesk/eardrum-server/errors"
)

// Products is the resolver for the products field.
func (r *categoryResolver) Products(ctx context.Context, obj *model.Category) ([]*model.Product, error) {
	id := uint(obj.ID)

	products, err := product.GetProductsForCategory(r.Sql.Db, &id)

	if err != nil {
		return nil, err
	}

	var productslist []*model.Product

	for _, product := range products {
		t := &model.Product{
			ID:                  int(product.GetID()),
			CreatedAt:           product.GetCreatedAt(),
			UpdatedAt:           product.GetUpdatedAt(),
			Name:                product.GetName(),
			PricePerUnitInCents: int(product.GetPricePerUnitInCents()),
		}
		productslist = append(productslist, t)
	}

	return productslist, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.NewCategory) (*model.Category, error) {
	s, err := auth.ForContext(ctx)
	if err != nil {
		return nil, errors.NewUnauthorizedError(err.Error())
	}
	if s == nil {
		return nil, errors.NewUnauthorizedError("access to create shop product category denied!")
	}
	role := s.GetRole()
	if role != "merchant" {
		return nil, errors.NewUnauthorizedError("access to create merchant product category denied. Only available for registered and logged in merchants")
	}
	id, err := s.GetID()

	if err != nil {
		errors.ErrPersistenceFailure("could not access merchant's id!")
	}

	category, err := product.CreateCategory(input, r.Sql.Db, uint(id))

	if err != nil {
		return nil, err
	}

	c := model.Category{
		ID:          int(category.GetID()),
		CreatedAt:   category.GetCreatedAt(),
		UpdatedAt:   category.GetUpdatedAt(),
		Name:        category.GetName(),
		Description: category.GetDescription(),
	}

	return &c, nil
}

// AddProductToCategory is the resolver for the addProductToCategory field.
func (r *mutationResolver) AddProductToCategory(ctx context.Context, productids []int, categoryid int) (*model.Category, error) {
	s, err := auth.ForContext(ctx)
	if err != nil {
		return nil, errors.NewUnauthorizedError(err.Error())
	}
	if s == nil {
		return nil, errors.NewUnauthorizedError("access to add merchant product to category denied!")
	}
	role := s.GetRole()
	if role != "merchant" {
		return nil, errors.NewUnauthorizedError("access to add merchant product to category denied. Only available for registered and logged in merchants")
	}

	id, err := s.GetID()

	if err != nil {
		errors.ErrPersistenceFailure("could not access merchant's id!")
	}

	var productslist []uint

	for _, productid := range productids {
		productslist = append(productslist, uint(productid))
	}

	err = product.AddProductsToCategory(r.Sql.Db, uint(id), uint(categoryid), productslist)

	if err != nil {
		return nil, err
	}

	category, err := product.GetCategoryWithId(r.Sql.Db, categoryid)

	if err != nil {
		return nil, err
	}

	c := model.Category{
		ID:          int(category.GetID()),
		CreatedAt:   category.GetCreatedAt(),
		UpdatedAt:   category.GetUpdatedAt(),
		Name:        category.GetName(),
		Description: category.GetDescription(),
	}

	return &c, nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, categoryid int) (bool, error) {
	s, err := auth.ForContext(ctx)
	if err != nil {
		return false, errors.NewUnauthorizedError(err.Error())
	}
	if s == nil {
		return false, errors.NewUnauthorizedError("access to delete merchant product category denied!")
	}
	role := s.GetRole()
	if role != "merchant" {
		return false, errors.NewUnauthorizedError("access to delete merchant product category denied. Only available for registered and logged in merchants")
	}
	id, err := s.GetID()

	if err != nil {
		errors.ErrPersistenceFailure("could not access merchant's id!")
	}

	err = product.DeleteCategory(r.Sql.Db, uint(id), uint(categoryid))

	if err != nil {
		return false, err
	}

	return true, nil
}

// RemoveProductsFromCategory is the resolver for the removeProductsFromCategory field.
func (r *mutationResolver) RemoveProductsFromCategory(ctx context.Context, productids []int, categoryid int) (*model.Category, error) {
	s, err := auth.ForContext(ctx)
	if err != nil {
		return nil, errors.NewUnauthorizedError(err.Error())
	}
	if s == nil {
		return nil, errors.NewUnauthorizedError("access to remove merchant product to category denied!")
	}
	role := s.GetRole()
	if role != "merchant" {
		return nil, errors.NewUnauthorizedError("access to remove merchant product to category denied. Only available for registered and logged in merchants")
	}

	id, err := s.GetID()

	if err != nil {
		errors.ErrPersistenceFailure("could not access merchant's id!")
	}

	var productslist []uint

	for _, productid := range productids {
		productslist = append(productslist, uint(productid))
	}

	err = product.RemoveProductsFromCategory(r.Sql.Db, uint(id), productslist)

	if err != nil {
		return nil, err
	}

	category, err := product.GetCategoryWithId(r.Sql.Db, categoryid)

	if err != nil {
		return nil, err
	}

	c := model.Category{
		ID:          int(category.GetID()),
		CreatedAt:   category.GetCreatedAt(),
		UpdatedAt:   category.GetUpdatedAt(),
		Name:        category.GetName(),
		Description: category.GetDescription(),
	}

	return &c, nil
}

// Category returns CategoryResolver implementation.
func (r *Resolver) Category() CategoryResolver { return &categoryResolver{r} }

type categoryResolver struct{ *Resolver }
