package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"errors"

	"github.com/GigaDesk/eardrum-server/auth"
	"github.com/GigaDesk/eardrum-server/graph/model"
	"github.com/GigaDesk/eardrum-server/shutdown"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.NewProduct) (*model.Product, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}
	s, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}
	if s == nil {
		return nil, errors.New("access to create shop product denied!")
	}
	role := s.GetRole()
	if role != "shop" {
		return nil, errors.New("access to create shop product denied. Only available for registered and logged in shops")
	}
	id, err := s.GetID()

	if err != nil {
		errors.New("could not access shop's id!")
	}

	product, err := product.CreateProduct(input, id, r.Sql.Db, r.Neo4j)

	if err != nil {
		return nil, errors.New("error creating product")
	}

	p := model.Product{
		ID:                  int(product.GetID()),
		CreatedAt:           product.GetCreatedAt(),
		UpdatedAt:           product.GetUpdatedAt(),
		Name:                product.GetName(),
		PricePerUnitInCents: int(product.GetPricePerUnitInCents()),
	}

	return &p, nil
}
