# Defines the Product type.
type Product {
  id: Int!
  createdAt: Time!
  updatedAt: Time!
  name: String!
  pricePerUnitInCents: Int!
  purchases: [Purchase!]
  category: Category!
}

# Fields required for adding a new product to the system.
input NewProduct {
  name: String!
  pricePerUnitInCents: Int!
}

# A new input type is created to handle the mutation for editing a product's price.
# It requires both the product's ID and the new price.
input EditProductPriceInput {
  id: Int!
  newPricePerUnitInCents: Int!
}

extend type Mutation {
  createProduct(input: NewProduct!): Product!
  editProductPrice(input: EditProductPriceInput!): Product!
  blockProduct(input: Int!): Boolean!
  deleteProduct(input: Int!): Boolean!
  unblockProduct(input: Int!): Boolean!
  restoreProduct(input: Int!): Boolean!
}
