package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"errors"

	"github.com/GigaDesk/eardrum-graph/neo4jproduct"
	"github.com/GigaDesk/eardrum-server/graph/model"
)

// Product is the resolver for the product field.
func (r *purchaseResolver) Product(ctx context.Context, obj *model.Purchase) (*model.Product, error) {
	product, err := neo4jproduct.RetrievePurchaseProduct(r.Neo4j, obj.ID)

	if err != nil {
		return nil, errors.New("could not access purchase's product!")
	}

	p := model.Product{
		ID:                  int(product.GetID()),
		CreatedAt:           product.GetCreatedAt(),
		UpdatedAt:           product.GetUpdatedAt(),
		Name:                product.GetName(),
		PricePerUnitInCents: int(product.GetPricePerUnitInCents()),
	}

	return &p, nil
}

// Purchase returns PurchaseResolver implementation.
func (r *Resolver) Purchase() PurchaseResolver { return &purchaseResolver{r} }

type purchaseResolver struct{ *Resolver }
