package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"

	"github.com/GigaDesk/eardrum-postgres/transaction"
	"github.com/GigaDesk/eardrum-server/graph/model"
	"github.com/GigaDesk/eardrum-server/errors"
)

// Product is the resolver for the product field.
func (r *purchaseResolver) Product(ctx context.Context, obj *model.Purchase) (*model.Product, error) {
	var purchase transaction.Purchase
	// The .Preload() method tells GORM to load the associated Product data
	// in the same query.
	if err := r.Sql.Db.
		Preload("Product").
		First(&purchase, obj.ID).Error; err != nil {
		return nil, errors.NewUnauthorizedError(err.Error())
	}

	product := &model.Product{
		ID:                  int(purchase.Product.ID),
		CreatedAt:           purchase.Product.CreatedAt,
		UpdatedAt:           purchase.Product.UpdatedAt,
		Name:                purchase.Product.Name,
		PricePerUnitInCents: int(purchase.Product.PricePerUnitInCents),
	}
	return product, nil
}

// Purchase returns PurchaseResolver implementation.
func (r *Resolver) Purchase() PurchaseResolver { return &purchaseResolver{r} }

type purchaseResolver struct{ *Resolver }
