package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"

	"github.com/GigaDesk/eardrum-server/graph/model"
)

// CreateDummy is the resolver for the createDummy field.
func (r *mutationResolver) CreateDummy(ctx context.Context, name string) (*model.Dummy, error) {
	panic(fmt.Errorf("not implemented: CreateDummy - createDummy"))
}

// GetDummys is the resolver for the getDummys field.
func (r *queryResolver) GetDummys(ctx context.Context) ([]*model.Dummy, error) {
	panic(fmt.Errorf("not implemented: GetDummys - getDummys"))
}

// GetDummy is the resolver for the getDummy field.
func (r *queryResolver) GetDummy(ctx context.Context, id *int) (*model.Dummy, error) {
	panic(fmt.Errorf("not implemented: GetDummy - getDummy"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
