package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/AlekSi/pointer"
	"github.com/GigaDesk/eardrum-graph/neo4jschool"
	"github.com/GigaDesk/eardrum-graph/neo4jstudent"
	"github.com/GigaDesk/eardrum-prefix/prefix"
	"github.com/GigaDesk/eardrum-prefix/validate"
	"github.com/GigaDesk/eardrum-server/auth"
	"github.com/GigaDesk/eardrum-server/encrypt"
	"github.com/GigaDesk/eardrum-server/graph/model"
	"github.com/GigaDesk/eardrum-server/phoneutils"
	"github.com/GigaDesk/eardrum-server/pkg/jwt"
	"github.com/GigaDesk/eardrum-server/shutdown"
	"github.com/GigaDesk/eardrum-server/wrappers"
	"github.com/rs/zerolog/log"
)

// CreateSchool is the resolver for the createSchool field, signs up a school to the system
func (r *mutationResolver) CreateSchool(ctx context.Context, input model.NewSchool) (*model.UnverifiedSchool, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}
	//validate inputs
	if err := input.Validate(); err != nil {
		return nil, err
	}
	//check if the phone number exists in the database
	phoneexists, err := phoneutils.CheckSchoolPhoneNumber(r.Sql.Db, input.PhoneNumber)

	//return any error that might be associated with checking the phone number's existence in the database
	if err != nil {
		log.Error().Str("phone_number", input.PhoneNumber).Str("path", "CreateSchool").Msg(err.Error())
		return nil, errors.New("error checking phone number's existence")
	}
	//return an error if phone number exists in the database
	if phoneexists.Verified == true || phoneexists.Unverified == true {
		return nil, errors.New("phone number already exists")
	}

	//encrypt input password
	encryptedpassword, err := encrypt.HashPassword(input.Password)
	if err != nil {
		log.Error().Str("password", input.Password).Str("path", "CreateSchool").Msg(err.Error())
		return nil, err
	}
	//create an unverified school data
	unverifiedschool := &model.UnverifiedSchool{
		Name:        input.Name,
		PhoneNumber: input.PhoneNumber,
		Password:    encryptedpassword,
		Badge:       input.Badge,
		Website:     input.Website,
	}
	//send an OTP code to the phone number associated with the unverified school record, return error id there is any
	if err := phoneutils.SendOtp(unverifiedschool.PhoneNumber); err != nil {
		log.Error().Str("phone_number", input.PhoneNumber).Str("path", "CreateSchool").Msg(err.Error())
		return nil, err
	}
	//create an unverified school record in the database and return if operation succeeds
	if err := r.Sql.Db.Create(unverifiedschool).Error; err != nil {
		log.Error().Str("name", input.Name).Str("path", "CreateSchool").Msg(err.Error())
		return nil, errors.New("an unexpected error occurred while creating the school account. please try again later or contact support")
	}

	return unverifiedschool, nil
}

// VerifySchool is the resolver for the verifySchool field. it checks the validity of an OTP code in relation to the phonenumber, if valid it transfers a school's data from the unverified_schools table to the school table
func (r *mutationResolver) VerifySchool(ctx context.Context, input model.Verificationinfo) (*model.School, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}
	//validate inputs
	if err := input.Validate(); err != nil {
		return nil, err
	}
	//Check the validity of an OTP code
	if err := phoneutils.CheckOtp(input.PhoneNumber, input.Otp); err != nil {
		return nil, err
	}
	//declare an unverifiedschool variable
	var unverifiedschool *model.UnverifiedSchool

	// Find the first unverified school that matches the input phone number from the unverified school table
	if err := r.Sql.Db.Where("phone_number = ?", input.PhoneNumber).First(&unverifiedschool).Error; err != nil {
		log.Info().Str("phone_number", input.PhoneNumber).Str("path", "VerifySchool").Msg("phone number does not exist")
		return nil, errors.New("error finding unverified school with phone number: " + input.PhoneNumber)
	}

	// transform the unverified school model into school model and copy it
	school := &model.School{
		Name:        unverifiedschool.Name,
		PhoneNumber: unverifiedschool.PhoneNumber,
		Password:    unverifiedschool.Password,
		Badge:       unverifiedschool.Badge,
		Website:     unverifiedschool.Website,
	}

	// take the newly transformed and copied school data and transfer it into the official verified school table
	if err := r.Sql.Db.Create(school).Error; err != nil {
		log.Info().Str("name", school.Name).Str("path", "VerifySchool").Msg(err.Error())
		return nil, errors.New("Failed to verify school account. please try again later or contact support")
	}

	s := wrappers.Neo4jSchoolWrapper{
		School: school,
	}
	//create the verified school record in Neo4j
	if err := neo4jschool.CreateSchool(r.Neo4j, s); err != nil {
		go shutdown.InitiateShutdown(err, "VerifySchool", s.ID)
		return nil, errors.New("a serious synchronization error occurred while verifying the school account. please try again later or contact support")
	}
	// delete the unverified school from the unverified school table
	if err := r.Sql.Db.Delete(unverifiedschool).Error; err != nil {
		log.Error().Str("path", "VerifySchool").Int("record_id", unverifiedschool.ID).Msg(err.Error())
		return nil, errors.New("Failed to complete school account verification. please try again later or contact support")
	}

	log.Info().Int("initial_record_id", unverifiedschool.ID).Int("final_record_id", school.ID).Str("path", "VerifySchool").Msg("completed unverified school to school data transaction")
	return school, nil
}

// SendCode is the resolver for the sendCode field, it send an otp code to the provided phone number
func (r *mutationResolver) SendCode(ctx context.Context, phoneNumber string) (*model.SendCodeStatus, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}
	//validate phone number
	if err := validate.ValidateKenyanPhoneNumber(phoneNumber); err != nil {
		return nil, err
	}

	if err := phoneutils.SendOtp(phoneNumber); err != nil {
		log.Error().Str("phone_number", phoneNumber).Str("path", "SendCode").Msg(err.Error())
		return nil, err
	}
	sendcodestatus := &model.SendCodeStatus{
		PhoneNumber: phoneNumber,
		Success:     true,
	}
	return sendcodestatus, nil
}

// SchoolLogin is the resolver for the schoolLogin field.
func (r *mutationResolver) SchoolLogin(ctx context.Context, input model.SchoolLogin) (*string, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}

	//validate SchoolLogin input
	if err := input.Validate(); err != nil {
		return nil, err
	}

	//declare a school variable
	var school *model.School
	// Find the first school that matches the input phone number from the school table

	if err := r.Sql.Db.Where("phone_number = ?", input.PhoneNumber).First(&school).Error; err != nil {
		log.Info().Str("phone_number", input.PhoneNumber).Str("path", "SchoolLogin").Msg(err.Error())
		return nil, errors.New("phone number does not exist")
	}
	//check if the password of the school matches the input password
	if err := encrypt.CheckPassword(school.Password, input.Password); err != nil {
		log.Info().Str("path", "SchoolLogin").Msg(err.Error())
		return nil, errors.New("Invalid phone number or password")
	}

	credentials := jwt.TokenCredentials{
		Id:   strconv.Itoa(school.ID),
		Role: "school",
	}
	token, err := jwt.GenerateToken(credentials)
	if err != nil {
		log.Error().Str("id", credentials.Id).Str("role", credentials.Role).Str("path", "SchoolLogin").Msg(err.Error())
		return nil, errors.New("error generating accessToken")
	}
	log.Info().Str("id", credentials.Id).Str("role", credentials.Role).Str("path", "SchoolLogin").Msg("school logged in successfully!")
	return &token, nil
}

// ForgotSchoolPassword is the resolver for the forgotSchoolPassword field.
func (r *mutationResolver) ForgotSchoolPassword(ctx context.Context, phoneNumber string) (*model.SendCodeStatus, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}

	//validate phone number
	if err := validate.ValidateKenyanPhoneNumber(phoneNumber); err != nil {
		return nil, err
	}

	//check if the phone number exists in the database
	phoneexists, err := phoneutils.CheckSchoolPhoneNumber(r.Sql.Db, phoneNumber)

	//return any error that might be associated with checking the phone number's existence in the database
	if err != nil {
		log.Error().Str("phone_number", phoneNumber).Str("path", "ForgotSchoolPassword").Msg(err.Error())
		return nil, err
	}
	//return an error if phone number exists in the unverified school table
	if phoneexists.Verified != true && phoneexists.Unverified == true {
		return nil, errors.New("phone number has been registered but is yet to be verified")
	}
	//return an error if phone number is neither registered nor verified
	if phoneexists.Verified != true && phoneexists.Unverified != true {
		return nil, errors.New("phone number does not exist")
	}
	//send an OTP code to the phone number provided, return error if there is any
	if err := phoneutils.SendOtp(phoneNumber); err != nil {
		log.Error().Str("phone_number", phoneNumber).Str("path", "ForgotSchoolPassword").Msg(err.Error())
		return nil, err
	}
	//return status on success
	sendcodestatus := &model.SendCodeStatus{
		PhoneNumber: phoneNumber,
		Success:     true,
	}
	return sendcodestatus, nil
}

// RequestSchoolPasswordReset is the resolver for the requestSchoolPasswordReset field.
func (r *mutationResolver) RequestSchoolPasswordReset(ctx context.Context, input *model.Verificationinfo) (*string, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}
	//validate inputs
	if err := input.Validate(); err != nil {
		return nil, err
	}

	//Check the validity of an OTP code
	if err := phoneutils.CheckOtp(input.PhoneNumber, input.Otp); err != nil {
		return nil, err
	}
	//declare a school variable
	var school *model.School

	// Find the first school that matches the input phone number from the school table

	if err := r.Sql.Db.Where("phone_number = ?", input.PhoneNumber).First(&school).Error; err != nil {
		log.Info().Str("phone_number", input.PhoneNumber).Str("path", "RequestSchoolPasswordReset").Msg(err.Error())
		return nil, errors.New("phone number does not exist")
	}

	credentials := jwt.TokenCredentials{
		Id:   strconv.Itoa(school.ID),
		Role: "school",
	}
	token, err := jwt.GenerateToken(credentials)
	if err != nil {
		log.Error().Str("id", credentials.Id).Str("role", credentials.Role).Str("path", "RequestSchoolPasswordReset").Msg(err.Error())
		return nil, errors.New("error generating accessToken")
	}
	return &token, nil
}

// ResetSchoolPassword is the resolver for the ResetSchoolPassword field.
func (r *mutationResolver) ResetSchoolPassword(ctx context.Context, newPassword string) (*model.School, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}
	user, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}
	if user == nil {
		return nil, errors.New("access to ResetSchoolPassword denied!")
	}
	role := user.GetRole()
	if role != "school" {
		return nil, errors.New("access to ResetSchoolPassword denied. Only available for registered and logged in schools. To fix check access token!")
	}
	id, err := user.GetID()

	if err != nil {
		errors.New("could not access school's id!")
	}

	//validate inputs
	if err := validate.ValidatePassword(newPassword); err != nil {
		return nil, err
	}

	var school *model.School
	//fetch the record to be updated from the database
	if err := r.Sql.Db.First(&school, id).Error; err != nil {
		log.Error().Int("id", id).Str("path", "ResetSchoolPassword").Msg(err.Error())
		return nil, err
	}
	//encrypt input password
	encryptedpassword, err := encrypt.HashPassword(newPassword)
	if err != nil {
		log.Error().Str("password", newPassword).Str("path", "ResetSchoolPassword").Msg(err.Error())
		return nil, err
	}
	// Update the records' attributes with `map`
	if err := r.Sql.Db.Model(&school).Updates(map[string]interface{}{"password": encryptedpassword}).Error; err != nil {
		log.Error().Int("id", school.ID).Str("path", "ResetSchoolPassword").Msg(fmt.Sprintf("updating school password failed: %s", err.Error()))
		return nil, err
	}

	//fetch the record again from the database, this time the updated version
	if err := r.Sql.Db.First(&school, id).Error; err != nil {
		log.Error().Int("id", id).Str("path", "ResetSchoolPassword").Msg(err.Error())
		return nil, err
	}

	//return the updated record
	return school, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input *model.RefreshTokenInput) (*string, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}
	credentials, err := jwt.ParseToken(input.Token)
	if err != nil {
		return nil, fmt.Errorf("access denied")
	}
	token, error := jwt.GenerateToken(*credentials)
	if error != nil {
		log.Error().Str("id", credentials.Id).Str("role", credentials.Role).Str("path", "RefreshToken").Msg(err.Error())
		return nil, error
	}
	return &token, nil
}

// SchoolPhoneNumberExists is the resolver for the schoolPhoneNumberExists field, checks if an school's phone number already exists in both the unverified_schools and schools tables
func (r *queryResolver) SchoolPhoneNumberExists(ctx context.Context, phoneNumber string) (*model.PhoneNumberExists, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}
	phoneexists, err := phoneutils.CheckSchoolPhoneNumber(r.Sql.Db, phoneNumber)

	if err != nil {
		log.Error().Str("phone_number", phoneNumber).Str("path", "SchoolPhoneNumberExists").Msg(err.Error())
		return nil, err
	}

	return phoneexists, nil
}

// GetSchoolProfile is the resolver for the getSchoolProfile field.
func (r *queryResolver) GetSchoolProfile(ctx context.Context) (*model.SchoolProfile, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}
	user, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}
	if user == nil {
		return nil, errors.New("access to getSchool profile denied!")
	}
	role := user.GetRole()
	if role != "school" {
		return nil, errors.New("access to getSchool profile denied. Only available for registered and logged in schools. To fix check access token!")
	}
	id, err := user.GetID()

	if err != nil {
		errors.New("could not access school's id!")
	}

	var school *model.School
	if err := r.Sql.Db.First(&school, id).Error; err != nil {
		log.Error().Int("id", id).Str("path", "GetSchoolProfile").Msg(err.Error())
		return nil, errors.New("could not access school's profile!")
	}
	log.Info().Int("id", id).Str("role", role).Str("path", "GetSchoolProfile").Msg("getting school's profile")
	schoolprofile := &model.SchoolProfile{
		ID:          school.ID,
		CreatedAt:   school.CreatedAt,
		UpdatedAt:   school.UpdatedAt,
		Name:        school.Name,
		PhoneNumber: school.PhoneNumber,
		Badge:       school.Badge,
		Website:     school.Website,
	}
	return schoolprofile, nil
}

// GetSchoolsProfile is the resolver for the getSchoolsProfile field.
func (r *queryResolver) GetSchoolsProfile(ctx context.Context) ([]*model.SchoolProfile, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}

	var schools []*model.School
	if err := r.Sql.Db.Find(&schools).Error; err != nil {
		log.Error().Str("path", "GetSchoolsProfile").Msg(err.Error())
		return nil, errors.New("could not access schools' profile!")
	}
	log.Info().Str("path", "GetSchoolProfile").Msg("getting schools' profile")

	var schoolsprofile []*model.SchoolProfile

	for _, school := range schools {
		schoolprofile := &model.SchoolProfile{
			ID:          school.ID,
			CreatedAt:   school.CreatedAt,
			UpdatedAt:   school.UpdatedAt,
			Name:        school.Name,
			PhoneNumber: school.PhoneNumber,
			Badge:       school.Badge,
			Website:     school.Website,
		}
		schoolsprofile = append(schoolsprofile, schoolprofile)
	}

	return schoolsprofile, nil
}

// Students is the resolver for the students field.
func (r *schoolProfileResolver) Students(ctx context.Context, obj *model.SchoolProfile) ([]*model.StudentProfile, error) {
	user, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}
	id, _ := user.GetID()
	neo4jstudents, err := neo4jstudent.RetrieveSchoolStudents(r.Neo4j, obj.ID)
	if err != nil {
		log.Error().Int("id", id).Str("role", user.Role).Msg(err.Error())
		return nil, errors.New("Failed to get school's students")
	}
	log.Info().Int("id", id).Str("role", user.GetRole()).Msg("getting school's students")
	var students []*model.StudentProfile
	for _, s := range neo4jstudents {
		student := &model.StudentProfile{
			ID:                 int(s.GetID()),
			CreatedAt:          s.GetCreatedAt(),
			UpdatedAt:          s.GetUpdatedAt(),
			RegistrationNumber: prefix.DePrefixWithId(s.GetRegistrationNumber(), obj.ID),
			Name:               s.GetName(),
			PhoneNumber:        s.GetPhoneNumber(),
			DateOfAdmission:    pointer.ToTimeOrNil(s.GetDateOfAdmission()),
			DateOfBirth:        pointer.ToTimeOrNil(s.GetDateofBirth()),
			ProfilePicture:     pointer.ToStringOrNil(s.GetProfilePicture()),
		}
		students = append(students, student)
	}
	if len(students) == 0 {
		return nil, nil
	}
	return students, nil
}

// SchoolProfile returns SchoolProfileResolver implementation.
func (r *Resolver) SchoolProfile() SchoolProfileResolver { return &schoolProfileResolver{r} }

type schoolProfileResolver struct{ *Resolver }
