package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"errors"
	"fmt"

	"github.com/GigaDesk/eardrum-prefix/validate"
	"github.com/GigaDesk/eardrum-server/graph/model"
	"github.com/GigaDesk/eardrum-server/phoneutils"
	"github.com/GigaDesk/eardrum-server/pkg/jwt"
	"github.com/GigaDesk/eardrum-server/shutdown"
	"github.com/rs/zerolog/log"
)

// CreateShop is the resolver for the createShop field.
func (r *mutationResolver) CreateShop(ctx context.Context, input model.NewShop) (*model.Shop, error) {
	panic(fmt.Errorf("not implemented: CreateShop - createShop"))
}

// VerifyShop is the resolver for the verifyShop field.
func (r *mutationResolver) VerifyShop(ctx context.Context, phoneNumber string, otp string) (*string, error) {
	panic(fmt.Errorf("not implemented: VerifyShop - verifyShop"))
}

// SendCode is the resolver for the sendCode field, it send an otp code to the provided phone number
func (r *mutationResolver) SendCode(ctx context.Context, phoneNumber string) (*model.SendCodeStatus, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}
	//validate phone number
	if err := validate.ValidateKenyanPhoneNumber(phoneNumber); err != nil {
		return nil, err
	}

	if err := phoneutils.SendOtp(phoneNumber); err != nil {
		log.Error().Str("phone_number", phoneNumber).Str("path", "SendCode").Msg(err.Error())
		return nil, err
	}
	sendcodestatus := &model.SendCodeStatus{
		PhoneNumber: phoneNumber,
		Success:     true,
	}
	return sendcodestatus, nil
}

// ShopLogin is the resolver for the shopLogin field.
func (r *mutationResolver) ShopLogin(ctx context.Context, phoneNumber string, password string) (*string, error) {
	panic(fmt.Errorf("not implemented: ShopLogin - shopLogin"))
}

// ForgotShopPassword is the resolver for the forgotShopPassword field.
func (r *mutationResolver) ForgotShopPassword(ctx context.Context, phoneNumber string) (*model.SendCodeStatus, error) {
	panic(fmt.Errorf("not implemented: ForgotShopPassword - forgotShopPassword"))
}

// RequestShopPasswordReset is the resolver for the requestShopPasswordReset field.
func (r *mutationResolver) RequestShopPasswordReset(ctx context.Context, phoneNumber string, otp string) (*string, error) {
	panic(fmt.Errorf("not implemented: RequestShopPasswordReset - requestShopPasswordReset"))
}

// ResetShopPassword is the resolver for the resetShopPassword field.
func (r *mutationResolver) ResetShopPassword(ctx context.Context, newPassword string) (*model.Shop, error) {
	panic(fmt.Errorf("not implemented: ResetShopPassword - resetShopPassword"))
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, token string) (*string, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}
	credentials, err := jwt.ParseToken(token)
	if err != nil {
		return nil, fmt.Errorf("access denied")
	}
	token, error := jwt.GenerateToken(*credentials)
	if error != nil {
		log.Error().Str("id", credentials.Id).Str("role", credentials.Role).Str("path", "RefreshToken").Msg(err.Error())
		return nil, error
	}
	return &token, nil
}

// GetShop is the resolver for the getShop field.
func (r *queryResolver) GetShop(ctx context.Context) (*model.Shop, error) {
	panic(fmt.Errorf("not implemented: GetShop - getShop"))
}

// GetShops is the resolver for the getShops field.
func (r *queryResolver) GetShops(ctx context.Context) ([]*model.Shop, error) {
	panic(fmt.Errorf("not implemented: GetShops - getShops"))
}

// Products is the resolver for the products field.
func (r *shopResolver) Products(ctx context.Context, obj *model.Shop) ([]*model.Product, error) {
	panic(fmt.Errorf("not implemented: Products - products"))
}

// Shop returns ShopResolver implementation.
func (r *Resolver) Shop() ShopResolver { return &shopResolver{r} }

type shopResolver struct{ *Resolver }
