package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	pgerror "errors"
	"fmt"
	"time"

	"github.com/GigaDesk/eardrum-postgres/merchant"
	"github.com/GigaDesk/eardrum-postgres/transaction"
	"github.com/GigaDesk/eardrum-prefix/validate"
	"github.com/GigaDesk/eardrum-server/auth"
	"github.com/GigaDesk/eardrum-server/encrypt"
	"github.com/GigaDesk/eardrum-server/graph/model"
	"github.com/GigaDesk/eardrum-server/phoneutils"
	"github.com/GigaDesk/eardrum-server/pkg/jwt"
	"github.com/rs/zerolog/log"
	"github.com/GigaDesk/eardrum-interfaces/errors"
)

// Transactions is the resolver for the transactions field.
func (r *merchantResolver) Transactions(ctx context.Context, obj *model.Merchant, limit *int, offset *int, startTime *time.Time, endTime *time.Time) ([]*model.Transaction, error) {
	transactions, err := transaction.GetTransactionsForMerchant(r.Sql.Db, obj.Username, limit, offset, startTime, endTime)

	if err != nil {
		return nil, err
	}

	var transactionslist []*model.Transaction

	for _, transaction := range transactions {
		t := &model.Transaction{
			TransactionID:          transaction.GetTransactionID(),
			CreatedAt:              transaction.GetCreatedAt(),
			UpdatedAt:              transaction.GetUpdatedAt(),
			TotalAmountInCents:     int(transaction.GetTotalAmountInCents()),
			TransactionCostInCents: int(transaction.GetTransactionCostInCents()),
		}
		transactionslist = append(transactionslist, t)
	}

	return transactionslist, nil
}

// CreateMerchant is the resolver for the createMerchant field.
func (r *mutationResolver) CreateMerchant(ctx context.Context, input model.NewMerchant) (*model.Merchant, error) {
	//validate inputs
	if err := input.Validate(); err != nil {
		return nil, err
	}

	//encrypt input password
	encryptedpassword, err := encrypt.HashPassword(input.Password)
	if err != nil {
		log.Error().Str("password", input.Password).Str("path", "CreateMerchant").Msg(err.Error())
		return nil, err
	}

	input.Password = encryptedpassword

	if err := phoneutils.SendOtp(input.PhoneNumber); err != nil {
		log.Error().Str("phone_number", input.PhoneNumber).Str("path", "CreateMerchant").Msg(err.Error())
		return nil, err
	}

	merchant, err := merchant.CreateMerchant(input, r.Sql.Db)

	if err != nil {
		log.Error().Str("username", input.Username).Str("path", "CreateMerchant").Msg(err.Error())
		return nil, err
	}

	u := model.Merchant{
		Username:              merchant.GetUserName(),
		PhoneNumber:           merchant.GetPhoneNumber(),
		AccountBalanceInCents: int(merchant.GetAccountBalanceInCents()),
	}

	return &u, nil
}

// VerifyMerchant is the resolver for the verifyMerchant field.
func (r *mutationResolver) VerifyMerchant(ctx context.Context, phoneNumber string, otp string) (*model.Authorization, error) {
	//Check the validity of the phone number
	if err := validate.ValidateKenyanPhoneNumber(phoneNumber); err != nil {
		return nil, err
	}

	//Check the validity of an OTP code
	if err := validate.ValidateOtp(otp); err != nil {
		return nil, err
	}
	if err := phoneutils.CheckOtp(phoneNumber, otp); err != nil {
		return nil, err
	}
	merchant, err := merchant.VerifyMerchant(phoneNumber, r.Sql.Db)

	if err != nil {
		log.Error().Str("phone_number", phoneNumber).Str("path", "VerifyMerchant").Msg(err.Error())
		return nil, err
	}

	credentials := jwt.TokenCredentials{
		Username: merchant.GetUserName(),
		Role:     "merchant",
	}
	token, err := jwt.GenerateToken(credentials)
	if err != nil {
		log.Error().Str("username", credentials.Username).Str("role", credentials.Role).Str("path", "VerifyMerchant").Msg(err.Error())
		return nil, err
	}
	log.Info().Str("username", credentials.Username).Str("role", credentials.Role).Str("path", "VerifyMerchant").Msg("merchant verified successfully!")

	return &model.Authorization{
		Token: token,
	}, nil
}

// SendCode is the resolver for the sendCode field, it send an otp code to the provided phone number
func (r *mutationResolver) SendCode(ctx context.Context, phoneNumber string) (*model.SendCodeStatus, error) {
	//validate phone number
	if err := validate.ValidateKenyanPhoneNumber(phoneNumber); err != nil {
		return nil, err
	}

	if err := phoneutils.SendOtp(phoneNumber); err != nil {
		log.Error().Str("phone_number", phoneNumber).Str("path", "SendCode").Msg(err.Error())
		return nil, err
	}
	sendcodestatus := &model.SendCodeStatus{
		PhoneNumber: phoneNumber,
		Success:     true,
	}
	return sendcodestatus, nil
}

// MerchantLogin is the resolver for the merchantLogin field.
func (r *mutationResolver) MerchantLogin(ctx context.Context, phoneNumber string, password string) (*model.Authorization, error) {
	// Find the merchant that matches the input phone number
	merchant, err := merchant.GetMerchantWithPhoneNumber(r.Sql.Db, phoneNumber)

	if err != nil {
		log.Info().Str("phone_number", phoneNumber).Str("path", "MerchantLogin").Msg(err.Error())
		return nil, err
	}
	//check if the password of the merchant matches the input password
	if err := encrypt.CheckPassword(merchant.GetPassword(), password); err != nil {
		log.Info().Str("path", "MerchantLogin").Msg(err.Error())
		return nil, err
	}

	credentials := jwt.TokenCredentials{
		Username: merchant.GetUserName(),
		Role:     "merchant",
	}
	token, err := jwt.GenerateToken(credentials)
	if err != nil {
		log.Error().Str("username", credentials.Username).Str("role", credentials.Role).Str("path", "MerchantLogin").Msg(err.Error())
		return nil, err
	}
	log.Info().Str("username", credentials.Username).Str("role", credentials.Role).Str("path", "MerchantLogin").Msg("merchant logged in successfully!")
	return &model.Authorization{
		Token: token,
	}, nil
}

// ForgotMerchantPassword is the resolver for the forgotMerchantPassword field.
func (r *mutationResolver) ForgotMerchantPassword(ctx context.Context, phoneNumber string) (*model.SendCodeStatus, error) {
	//validate phone number
	if err := validate.ValidateKenyanPhoneNumber(phoneNumber); err != nil {
		return nil, err
	}

	//check if the phone number exists in the database
	phoneexists, err := merchant.CheckMerchantPhoneNumber(r.Sql.Db, phoneNumber)

	//return any error that might be associated with checking the phone number's existence in the database
	if err != nil {
		log.Error().Str("phone_number", phoneNumber).Str("path", "ForgotMerchantPassword").Msg(err.Error())
		return nil, err
	}
	//return an error if phone number does not exist in verified form
	if phoneexists.IsVerified == false {
		err1 := errors.New(errors.EARMerchantNotFoundByPhone, pgerror.New("phone number does not exist in verified form"))
		err1.Log()
		return nil, err1
	}

	//send an OTP code to the phone number provided, return error if there is any
	if err := phoneutils.SendOtp(phoneNumber); err != nil {
		log.Error().Str("phone_number", phoneNumber).Str("path", "ForgotMerchantPassword").Msg(err.Error())
		return nil, err
	}
	//return status on success
	sendcodestatus := &model.SendCodeStatus{
		PhoneNumber: phoneNumber,
		Success:     true,
	}
	return sendcodestatus, nil
}

// RequestMerchantPasswordReset is the resolver for the requestMerchantPasswordReset field.
func (r *mutationResolver) RequestMerchantPasswordReset(ctx context.Context, phoneNumber string, otp string) (*model.Authorization, error) {
	//Check the validity of an OTP code
	if err := phoneutils.CheckOtp(phoneNumber, otp); err != nil {
		return nil, err
	}

	merchant, err := merchant.GetMerchantWithPhoneNumber(r.Sql.Db, phoneNumber)

	if err != nil {
		log.Info().Str("phone_number", phoneNumber).Str("path", "RequestMerchantPasswordReset").Msg(err.Error())
		return nil, err
	}

	credentials := jwt.TokenCredentials{
		Username: merchant.GetUserName(),
		Role:     "merchant",
	}
	token, err := jwt.GenerateToken(credentials)
	if err != nil {
		log.Error().Str("username", credentials.Username).Str("role", credentials.Role).Str("path", "RequestMerchantPasswordReset").Msg(err.Error())
		return nil, err
	}
	return &model.Authorization{
		Token: token,
	}, nil
}

// ResetMerchantPassword is the resolver for the resetMerchantPassword field.
func (r *mutationResolver) ResetMerchantPassword(ctx context.Context, newPassword string) (*model.Merchant, error) {
	s, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}

	role := s.GetRole()
	if role != "merchant" {
		err1 := errors.New(errors.EARMerchantUnauthenticated, pgerror.New("access to reset merchant password denied"))
		err1.Log()
		return nil, err1
	}
	username := s.GetUsername()

	//validate inputs
	if err := validate.ValidatePassword(newPassword); err != nil {
		return nil, err
	}

	encryptedpassword, err := encrypt.HashPassword(newPassword)

	if err != nil {
		return nil, err
	}

	merchant, err := merchant.UpdatePassword(r.Sql.Db, encryptedpassword, username)
	if err != nil {
		log.Error().Str("username", username).Str("path", "ResetMerchantPassword").Msg(err.Error())
		return nil, err
	}

	merchant1 := model.Merchant{
		Username:              merchant.GetUserName(),
		PhoneNumber:           merchant.GetPhoneNumber(),
		AccountBalanceInCents: int(merchant.GetAccountBalanceInCents()),
	}

	//return the updated record
	return &merchant1, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, token string) (*model.Authorization, error) {
	credentials, err := jwt.ParseToken(token)
	if err != nil {
		return nil, err
	}
	token, error := jwt.GenerateToken(*credentials)
	if error != nil {
		log.Error().Str("username", credentials.Username).Str("role", credentials.Role).Str("path", "RefreshToken").Msg(err.Error())
		return nil, err
	}
	return &model.Authorization{
		Token: token,
	}, nil
}

// UpdateMerchantPinCode is the resolver for the updateMerchantPinCode field.
func (r *mutationResolver) UpdateMerchantPinCode(ctx context.Context, newPincode string) (*model.Merchant, error) {
	u, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}

	role := u.GetRole()
	if role != "merchant" {
		err1 := errors.New(errors.EARMerchantUnauthenticated, pgerror.New("access to Update merchant PinCode denied"))
		err1.Log()
		return nil, err1
	}
	username := u.GetUsername()

	encryptedpincode, err := encrypt.HashPassword(newPincode)

	if err != nil {
		return nil, err
	}

	user2, err := merchant.UpdatePinCode(r.Sql.Db, encryptedpincode, username)
	if err != nil {
		log.Error().Str("username", username).Str("path", "UpdateMerchantPinCode").Msg(err.Error())
		return nil, err
	}

	merchant := model.Merchant{
		Username:              user2.GetUserName(),
		PhoneNumber:           user2.GetPhoneNumber(),
		AccountBalanceInCents: int(user2.GetAccountBalanceInCents()),
	}

	//return the updated record
	return &merchant, nil
}

// GetMerchant is the resolver for the getMerchant field.
func (r *queryResolver) GetMerchant(ctx context.Context) (*model.Merchant, error) {
	user, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}
	if user == nil {
		err1 := errors.New(errors.EARMerchantUnauthenticated, pgerror.New("access to get merchant profile denied!"))
		err1.Log()
		return nil, err1
	}
	role := user.GetRole()
	if role != "merchant" {
		err1 := errors.New(errors.EARMerchantUnauthenticated, pgerror.New("access to get merchant profile denied!"))
		err1.Log()
		return nil, err1
	}
	username := user.GetUsername()

	s, err := merchant.GetMerchantWithUserName(r.Sql.Db, username)
	if err != nil {
		log.Error().Str("username", username).Str("path", "GetMerchant").Msg(err.Error())
		return nil, err
	}
	log.Info().Str("username", username).Str("role", role).Str("path", "GetMerchant").Msg("getting merchant's profile")

	merchantprofile := model.Merchant{
		Username:              s.GetUserName(),
		PhoneNumber:           s.GetPhoneNumber(),
		AccountBalanceInCents: int(s.GetAccountBalanceInCents()),
	}
	return &merchantprofile, nil
}

// GetMerchants is the resolver for the getMerchants field.
func (r *queryResolver) GetMerchants(ctx context.Context) ([]*model.Merchant, error) {
	panic(fmt.Errorf("not implemented: GetMerchants - getMerchants"))
}

// Merchant returns MerchantResolver implementation.
func (r *Resolver) Merchant() MerchantResolver { return &merchantResolver{r} }

type merchantResolver struct{ *Resolver }