#returns a merchant's data
type Merchant {
  id: Int!
  createdAt: Time!
  updatedAt: Time!
  username: String!
  phone_number: String!
  mpesa_number: String
  account_balance_in_cents: Int!
  products: [Product!]
  categories: [Category!]
  category(id: Int!): Category
  transactions: [Transaction!]
}

#fields required for adding a new merchant to the system
input NewMerchant {
  username: String!
  phone_number: String!
  password: String!
  mpesa_number: String
}

#returns the status of sending an OTP code to a specific number
type SendCodeStatus {
  phone_number: String!
  success: Boolean!
}

extend type Query {
  getMerchant: Merchant
  getMerchants: [Merchant!]
}

extend type Mutation {
  createMerchant(input: NewMerchant!): Merchant
  verifyMerchant(phone_number: String!, otp: String!): Authorization!
  sendCode(phone_number: String!): SendCodeStatus
  merchantLogin(phone_number: String!, password: String!): Authorization!
  forgotMerchantPassword(phone_number: String!): SendCodeStatus
  requestMerchantPasswordReset(phone_number: String!, otp: String!): Authorization!
  resetMerchantPassword(new_password: String!): Merchant
  refreshToken(token: String!): Authorization!
  updateMerchantPinCode(new_pincode: String!): Merchant!
}
