#returns a transaction's data
type Transaction {
  transaction_id: String!
  createdAt: Time!
  updatedAt: Time!
  total_amount_in_cents: Int!
  transaction_cost_in_cents: Int!
  user_username: String!
  merchant_username: String!
  Device_Model: String
  user: User
}



#fields required for adding a new realtime transaction to the system
input NewOnlineTransaction {
  amount_in_cents: Int!
  qr_code: String!
  facial_embedding: String!
}


#fields required for adding a batch of offline transactions to the system
input NewOfflineTransaction {
  amount_in_cents: Int!
  qr_code: String!
  facial_embedding: String!
  phone_number: String!
  OfflineTimeStamp: Time!
  ScanLog: String!
  OfflineTransactionID: String!
}


extend type Mutation {
  createOnlineTransaction(input: NewOnlineTransaction!): Transaction
  createOfflineTransactions(input: [NewOfflineTransaction!]!): [Transaction!]
}