#returns a transaction's data
type TransactionShop{
  name: String!
}

type TransactionUser{
  name: String!
}

type Transaction {
  id: Int!
  createdAt: Time!
  updatedAt: Time!
  total_amount_in_cents: Int!
  transaction_cost_in_cents: Int!
  purchases: [Purchase!]!
  user: TransactionUser!
  shop: TransactionShop!
}

input PurchasedProduct {
   product_id: Int!
   units_bought: Int!
}

#fields required for adding a new product based transaction to the system
input NewProductTransaction {
  purchased_products: [PurchasedProduct!]!
  qr_code: String!
  pin_code: String!
}

#fields required for adding a new amount based transaction to the system
input NewAmountTransaction {
  amount_in_cents: Int!
  qr_code: String!
  pin_code: String!
}

extend type Mutation {
  createProductTransaction(input: NewProductTransaction!): Transaction
  createAmountTransaction(input: NewAmountTransaction!): Transaction
}