package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"errors"

	"github.com/GigaDesk/eardrum-graph/neo4jpurchase"
	"github.com/GigaDesk/eardrum-server/auth"
	"github.com/GigaDesk/eardrum-server/encrypt"
	"github.com/GigaDesk/eardrum-server/graph/model"
	"github.com/GigaDesk/eardrum-server/shutdown"
	"github.com/GigaDesk/eardrum-sync/transaction"
)

// CreateTransaction is the resolver for the createTransaction field.
func (r *mutationResolver) CreateTransaction(ctx context.Context, input model.NewTransaction) (*model.Transaction, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}
	s, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}
	if s == nil {
		return nil, errors.New("access to create transaction denied!")
	}
	role := s.GetRole()
	if role != "shop" {
		return nil, errors.New("access to create transaction denied. Only available for registered and logged in shops")
	}
	id, err := s.GetID()

	if err != nil {
		errors.New("could not access shop's id!")
	}

	t, err := transaction.CreateTransaction(input, id, func(hashedPIN, PIN string) error {
		err := encrypt.CheckPassword(hashedPIN, PIN)

		if err != nil {
			return err
		}
		return nil
	}, r.Sql.Db, r.Neo4j)

	if err != nil {
		return nil, err
	}

	p := model.Transaction{
		ID:                     int(t.GetID()),
		CreatedAt:              t.GetCreatedAt(),
		UpdatedAt:              t.GetUpdatedAt(),
		TotalAmountInCents:     int(t.GetTotalAmountInCents()),
		TransactionCostInCents: int(t.GetTransactionCostInCents()),
	}

	return &p, nil
}

// Purchases is the resolver for the purchases field.
func (r *transactionResolver) Purchases(ctx context.Context, obj *model.Transaction) ([]*model.Purchase, error) {
	purchases, err := neo4jpurchase.RetrieveTransactionPurchases(r.Neo4j, obj.ID)

	if err != nil {
		return nil, errors.New("could not access transactions' purchases!")
	}

	var purchaseslist []*model.Purchase

	for _, purchase := range purchases {
		p := &model.Purchase{
			ID:                 int(purchase.GetID()),
			UnitsBought:        purchase.GetUnitsBought(),
			TotalAmountInCents: int(purchase.GetTotalAmountInCents()),
		}
		purchaseslist = append(purchaseslist, p)
	}

	return purchaseslist, nil
}

// Transaction returns TransactionResolver implementation.
func (r *Resolver) Transaction() TransactionResolver { return &transactionResolver{r} }

type transactionResolver struct{ *Resolver }
