package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"

	"github.com/GigaDesk/eardrum-postgres/transaction"
	"github.com/GigaDesk/eardrum-server/auth"
	"github.com/GigaDesk/eardrum-server/encrypt"
	"github.com/GigaDesk/eardrum-server/graph/model"
	"github.com/GigaDesk/eardrum-server/errors"
)

// CreateProductTransaction is the resolver for the createProductTransaction field.
func (r *mutationResolver) CreateProductTransaction(ctx context.Context, input model.NewProductTransaction) (*model.Transaction, error) {
	s, err := auth.ForContext(ctx)
	if err != nil {
		return nil, errors.NewUnauthorizedError(err.Error())
	}
	if s == nil {
		return nil, errors.NewUnauthorizedError("access to create transaction denied!")
	}
	role := s.GetRole()
	if role != "merchant" {
		return nil, errors.NewUnauthorizedError("access to create transaction denied. Only available for registered and logged in merchants")
	}
	id, err := s.GetID()

	if err != nil {
		errors.ErrPersistenceFailure("could not access merchant's id!")
	}

	t, err := transaction.ProcessOrder(r.Sql.Db, uint(id), input, func(hashedPIN, PIN string) error {
		err := encrypt.CheckPassword(hashedPIN, PIN)

		if err != nil {
			return err
		}
		return nil
	})

	if err != nil {
		return nil, err
	}

	p := model.Transaction{
		ID:                     int(t.GetID()),
		CreatedAt:              t.GetCreatedAt(),
		UpdatedAt:              t.GetUpdatedAt(),
		TotalAmountInCents:     int(t.GetTotalAmountInCents()),
		TransactionCostInCents: int(t.GetTransactionCostInCents()),
	}

	return &p, nil
}

// CreateAmountTransaction is the resolver for the createAmountTransaction field.
func (r *mutationResolver) CreateAmountTransaction(ctx context.Context, input model.NewAmountTransaction) (*model.Transaction, error) {
	s, err := auth.ForContext(ctx)
	if err != nil {
		return nil, errors.NewUnauthorizedError(err.Error())
	}
	if s == nil {
		return nil, errors.NewUnauthorizedError("access to create transaction denied!")
	}
	role := s.GetRole()
	if role != "merchant" {
		return nil, errors.NewUnauthorizedError("access to create transaction denied. Only available for registered and logged in merchants")
	}
	id, err := s.GetID()

	if err != nil {
		errors.ErrPersistenceFailure("could not access merchant's id!")
	}

	t, err := transaction.ProcessTransaction(r.Sql.Db, uint(id), input, func(hashedPIN, PIN string) error {
		err := encrypt.CheckPassword(hashedPIN, PIN)

		if err != nil {
			return err
		}
		return nil
	})

	if err != nil {
		return nil, err
	}

	p := model.Transaction{
		ID:                     int(t.GetID()),
		CreatedAt:              t.GetCreatedAt(),
		UpdatedAt:              t.GetUpdatedAt(),
		TotalAmountInCents:     int(t.GetTotalAmountInCents()),
		TransactionCostInCents: int(t.GetTransactionCostInCents()),
	}

	return &p, nil
}

// Purchases is the resolver for the purchases field.
func (r *transactionResolver) Purchases(ctx context.Context, obj *model.Transaction) ([]*model.Purchase, error) {
	purchases, err := transaction.GetPurchasesForTransaction(r.Sql.Db, uint(obj.ID))

	if err != nil {
		return nil, err
	}

	var purchaseslist []*model.Purchase

	for _, purchase := range purchases {
		p := &model.Purchase{
			ID:                 int(purchase.GetID()),
			UnitsBought:        purchase.GetUnitsBought(),
			TotalAmountInCents: int(purchase.GetTotalAmountInCents()),
		}
		purchaseslist = append(purchaseslist, p)
	}

	return purchaseslist, nil
}

// User is the resolver for the user field.
func (r *transactionResolver) User(ctx context.Context, obj *model.Transaction) (*model.TransactionUser, error) {
	var transaction transaction.Transaction
	// The .Preload() method tells GORM to load the associated User data
	// in the same query.
	if err := r.Sql.Db.
		Preload("User").
		First(&transaction, obj.ID).Error; err != nil {
		return nil, errors.ErrPersistenceFailure(err.Error())
	}

	user := &model.TransactionUser{
		Username: transaction.User.UserName,
	}
	return user, nil
}

// Merchant is the resolver for the merchant field.
func (r *transactionResolver) Merchant(ctx context.Context, obj *model.Transaction) (*model.TransactionMerchant, error) {
	var transaction transaction.Transaction
	// The .Preload() method tells GORM to load the associated Shop data
	// in the same query.
	if err := r.Sql.Db.
		Preload("Merchant").
		First(&transaction, obj.ID).Error; err != nil {
		return nil, errors.ErrPersistenceFailure(err.Error())
	}

	merchant := &model.TransactionMerchant{
		Username: transaction.User.UserName,
	}
	return merchant, nil
}

// Transaction returns TransactionResolver implementation.
func (r *Resolver) Transaction() TransactionResolver { return &transactionResolver{r} }

type transactionResolver struct{ *Resolver }
