package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"errors"
	"strconv"

	"github.com/GigaDesk/eardrum-graph/neo4jtransaction"
	"github.com/GigaDesk/eardrum-postgres/postgresuser"
	"github.com/GigaDesk/eardrum-prefix/validate"
	"github.com/GigaDesk/eardrum-server/auth"
	"github.com/GigaDesk/eardrum-server/encrypt"
	"github.com/GigaDesk/eardrum-server/graph/model"
	"github.com/GigaDesk/eardrum-server/phoneutils"
	"github.com/GigaDesk/eardrum-server/pkg/jwt"
	"github.com/GigaDesk/eardrum-server/shutdown"
	"github.com/GigaDesk/eardrum-sync/user"
	"github.com/rs/zerolog/log"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}
	//validate inputs
	if err := input.Validate(); err != nil {
		return nil, err
	}

	//encrypt input password
	encryptedpassword, err := encrypt.HashPassword(input.Password)
	if err != nil {
		log.Error().Str("password", input.Password).Str("path", "CreateUser").Msg(err.Error())
		return nil, err
	}

	input.Password = encryptedpassword

	if err := phoneutils.SendOtp(input.PhoneNumber); err != nil {
		log.Error().Str("phone_number", input.PhoneNumber).Str("path", "CreateUser").Msg(err.Error())
		return nil, err
	}

	user, err := postgresuser.CreateUser(input, r.Sql.Db)

	if err != nil {
		log.Error().Str("name", input.Name).Str("path", "CreateUser").Msg(err.Error())
		return nil, errors.New("an unexpected error occurred while creating the user account. please try again later or contact support")
	}

	u := model.User{
		ID:                    int(user.GetID()),
		CreatedAt:             user.GetCreatedAt(),
		UpdatedAt:             user.GetUpdatedAt(),
		Name:                  user.GetName(),
		PhoneNumber:           user.GetPhoneNumber(),
		AccountBalanceInCents: int(user.GetAccountBalanceInCents()),
	}

	return &u, nil
}

// VerifyUser is the resolver for the verifyUser field.
func (r *mutationResolver) VerifyUser(ctx context.Context, phoneNumber string, otp string) (*string, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}
	//Check the validity of the phone number
	if err := validate.ValidateKenyanPhoneNumber(phoneNumber); err != nil {
		return nil, err
	}

	//Check the validity of an OTP code
	if err := validate.ValidateOtp(otp); err != nil {
		return nil, err
	}
	if err := phoneutils.CheckOtp(phoneNumber, otp); err != nil {
		return nil, err
	}
	user, err := user.VerifyUser(phoneNumber, r.Sql.Db, r.Neo4j)

	if err != nil {
		log.Error().Str("phone_number", phoneNumber).Str("path", "VerifyUser").Msg(err.Error())
		return nil, errors.New("an unexpected error occurred while verifying the user account. please try again later or contact support")
	}

	credentials := jwt.TokenCredentials{
		Id:   strconv.Itoa(int(user.GetID())),
		Role: "user",
	}
	token, err := jwt.GenerateToken(credentials)
	if err != nil {
		log.Error().Str("id", credentials.Id).Str("role", credentials.Role).Str("path", "VerifyUser").Msg(err.Error())
		return nil, errors.New("error generating accessToken")
	}
	log.Info().Str("id", credentials.Id).Str("role", credentials.Role).Str("path", "VerifyUser").Msg("user verified successfully!")

	return &token, nil
}

// UserLogin is the resolver for the userLogin field.
func (r *mutationResolver) UserLogin(ctx context.Context, phoneNumber string, password string) (*string, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}

	// Find the user that matches the input phone number
	user, err := postgresuser.GetUserWithPhoneNumber(r.Sql.Db, phoneNumber)

	if err != nil {
		log.Info().Str("phone_number", phoneNumber).Str("path", "UserLogin").Msg(err.Error())
		return nil, errors.New("phone number does not exist")
	}
	//check if the password of the user matches the input password
	if err := encrypt.CheckPassword(user.GetPassword(), password); err != nil {
		log.Info().Str("path", "UserLogin").Msg(err.Error())
		return nil, errors.New("Invalid phone number or password")
	}

	credentials := jwt.TokenCredentials{
		Id:   strconv.Itoa(int(user.GetID())),
		Role: "user",
	}
	token, err := jwt.GenerateToken(credentials)
	if err != nil {
		log.Error().Str("id", credentials.Id).Str("role", credentials.Role).Str("path", "UserLogin").Msg(err.Error())
		return nil, errors.New("error generating accessToken")
	}
	log.Info().Str("id", credentials.Id).Str("role", credentials.Role).Str("path", "UserLogin").Msg("user logged in successfully!")
	return &token, nil
}

// ForgotUserPassword is the resolver for the forgotUserPassword field.
func (r *mutationResolver) ForgotUserPassword(ctx context.Context, phoneNumber string) (*model.SendCodeStatus, error) {
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}

	//validate phone number
	if err := validate.ValidateKenyanPhoneNumber(phoneNumber); err != nil {
		return nil, err
	}

	//check if the phone number exists in the database
	phoneexists, err := postgresuser.CheckUserPhoneNumber(r.Sql.Db, phoneNumber)

	//return any error that might be associated with checking the phone number's existence in the database
	if err != nil {
		log.Error().Str("phone_number", phoneNumber).Str("path", "ForgotUserPassword").Msg(err.Error())
		return nil, err
	}
	//return an error if phone number exists in the unverified school table
	if phoneexists.Verified != true && phoneexists.Unverified == true {
		return nil, errors.New("phone number has been registered but is yet to be verified")
	}
	//return an error if phone number is neither registered nor verified
	if phoneexists.Verified != true && phoneexists.Unverified != true {
		return nil, errors.New("phone number does not exist")
	}
	//send an OTP code to the phone number provided, return error if there is any
	if err := phoneutils.SendOtp(phoneNumber); err != nil {
		log.Error().Str("phone_number", phoneNumber).Str("path", "ForgotUserPassword").Msg(err.Error())
		return nil, err
	}
	//return status on success
	sendcodestatus := &model.SendCodeStatus{
		PhoneNumber: phoneNumber,
		Success:     true,
	}
	return sendcodestatus, nil
}

// RequestUserPasswordReset is the resolver for the requestUserPasswordReset field.
func (r *mutationResolver) RequestUserPasswordReset(ctx context.Context, phoneNumber string, otp string) (*string, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}

	//Check the validity of an OTP code
	if err := phoneutils.CheckOtp(phoneNumber, otp); err != nil {
		return nil, err
	}

	user, err := postgresuser.GetUserWithPhoneNumber(r.Sql.Db, phoneNumber)

	if err != nil {
		log.Info().Str("phone_number", phoneNumber).Str("path", "RequestUserPasswordReset").Msg(err.Error())
		return nil, errors.New("phone number does not exist")
	}

	credentials := jwt.TokenCredentials{
		Id:   strconv.Itoa(int(user.GetID())),
		Role: "user",
	}
	token, err := jwt.GenerateToken(credentials)
	if err != nil {
		log.Error().Str("id", credentials.Id).Str("role", credentials.Role).Str("path", "RequestUserPasswordReset").Msg(err.Error())
		return nil, errors.New("error generating accessToken")
	}
	return &token, nil
}

// ResetUserPassword is the resolver for the resetUserPassword field.
func (r *mutationResolver) ResetUserPassword(ctx context.Context, newPassword string) (*model.User, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}
	u, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}
	if u == nil {
		return nil, errors.New("access to ResetUserPassword denied!")
	}
	role := u.GetRole()
	if role != "user" {
		return nil, errors.New("access to ResetUserPassword denied. Only available for registered and logged in users")
	}
	id, err := u.GetID()

	if err != nil {
		errors.New("could not access user's id!")
	}

	//validate inputs
	if err := validate.ValidatePassword(newPassword); err != nil {
		return nil, err
	}

	encryptedpassword, err := encrypt.HashPassword(newPassword)

	if err != nil {
		return nil, err
	}

	user, err := user.UpdatePassword(r.Sql.Db, encryptedpassword, id, r.Neo4j)
	if err != nil {
		log.Error().Int("id", id).Str("path", "ResetUserPassword").Msg(err.Error())
		return nil, err
	}

	user1 := model.User{
		ID:                    int(user.GetID()),
		CreatedAt:             user.GetCreatedAt(),
		UpdatedAt:             user.GetUpdatedAt(),
		Name:                  user.GetName(),
		PhoneNumber:           user.GetPhoneNumber(),
		AccountBalanceInCents: int(user.GetAccountBalanceInCents()),
	}

	//return the updated record
	return &user1, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context) (*model.User, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}
	user, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}
	if user == nil {
		return nil, errors.New("access to get user profile denied!")
	}
	role := user.GetRole()
	if role != "user" {
		return nil, errors.New("access to get user profile denied. Only available for registered and logged in users.")
	}
	id, err := user.GetID()

	if err != nil {
		errors.New("could not access user's id!")
	}

	u, err := postgresuser.GetUserWithId(r.Sql.Db, id)
	if err != nil {
		log.Error().Int("id", id).Str("path", "GetUser").Msg(err.Error())
		return nil, errors.New("could not access user's profile!")
	}
	log.Info().Int("id", id).Str("role", role).Str("path", "GetUser").Msg("getting user's profile")

	userprofile := model.User{
		ID:                    int(u.GetID()),
		CreatedAt:             u.GetCreatedAt(),
		UpdatedAt:             u.GetUpdatedAt(),
		Name:                  u.GetName(),
		PhoneNumber:           u.GetPhoneNumber(),
		AccountBalanceInCents: int(u.GetAccountBalanceInCents()),
	}
	return &userprofile, nil
}

// GetUsers is the resolver for the getUsers field.
func (r *queryResolver) GetUsers(ctx context.Context) ([]*model.User, error) {
	//check if system is in shutdown mode
	if *shutdown.IsShutdown {
		return nil, errors.New("System is shut down for maintainance. We are sorry for any incoveniences caused")
	}

	users, err := postgresuser.GetUsers(r.Sql.Db)

	if err != nil {
		log.Error().Str("path", "GetUsers").Msg(err.Error())
		return nil, errors.New("could not access users' profile!")
	}

	var usersprofile []*model.User

	for _, user := range users {
		userprofile := &model.User{
			ID:                    int(user.GetID()),
			CreatedAt:             user.GetCreatedAt(),
			UpdatedAt:             user.GetUpdatedAt(),
			Name:                  user.GetName(),
			PhoneNumber:           user.GetPhoneNumber(),
			AccountBalanceInCents: int(user.GetAccountBalanceInCents()),
		}
		usersprofile = append(usersprofile, userprofile)
	}

	return usersprofile, nil
}

// Transactions is the resolver for the transactions field.
func (r *userResolver) Transactions(ctx context.Context, obj *model.User) ([]*model.Transaction, error) {
	transactions, err := neo4jtransaction.RetrieveUserTransactions(r.Neo4j, obj.ID)

	if err != nil {
		return nil, errors.New("could not access users' transactions!")
	}

	var transactionslist []*model.Transaction

	for _, transaction := range transactions {
		t := &model.Transaction{
			ID:                     int(transaction.GetID()),
			CreatedAt:              transaction.GetCreatedAt(),
			UpdatedAt:              transaction.GetUpdatedAt(),
			TotalAmountInCents:     int(transaction.GetTotalAmountInCents()),
			TransactionCostInCents: int(transaction.GetTransactionCostInCents()),
		}
		transactionslist = append(transactionslist, t)
	}

	return transactionslist, nil
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
