#returns a user's data
type User {
  username: String!
  phone_number: String!
  qr_code: String!
  facial_embeddings: [String!]
  account_balance_in_cents: Int!
    transactions(
    limit: Int = 10
    offset: Int = 0
    startTime: Time
    endTime: Time
  ): [Transaction!]
}

#fields required for adding a new user to the system
input NewUser {
  username: String!
  phone_number: String!
  password: String!
}

extend type Query {
  getUser: User
}

extend type Mutation {
  createUser(input: NewUser!): User!
  verifyUser(phone_number: String!, otp: String!): Authorization!
  userLogin(phone_number: String!, password: String!): Authorization!
  forgotUserPassword(phone_number: String!): SendCodeStatus!
  requestUserPasswordReset(phone_number: String!, otp: String!): Authorization!
  resetUserPassword(new_password: String!): User!
  updateUserPinCode(new_pincode: String!): User!
  regenerateUserQrCode: User!
}
