package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	pgerror"errors"
	"time"

	"github.com/AlekSi/pointer"
	"github.com/Lcat-Technologies/eardrum-interfaces/errors"
	"github.com/Lcat-Technologies/eardrum-postgres/transaction"
	"github.com/Lcat-Technologies/eardrum-postgres/user"
	"github.com/Lcat-Technologies/eardrum-prefix/validate"
	"github.com/Lcat-Technologies/eardrum-server/auth"
	"github.com/Lcat-Technologies/eardrum-server/encrypt"
	"github.com/Lcat-Technologies/eardrum-server/graph/model"
	"github.com/Lcat-Technologies/eardrum-server/phoneutils"
	"github.com/Lcat-Technologies/eardrum-server/pkg/jwt"
	"github.com/rs/zerolog/log"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	//validate inputs
	if err := input.Validate(); err != nil {
		return nil, err
	}

	//encrypt input password
	encryptedpassword, err := encrypt.HashPassword(input.Password)
	if err != nil {
		log.Error().Str("password", input.Password).Str("path", "CreateUser").Msg(err.Error())
		return nil, err
	}

	input.Password = encryptedpassword

	user, err := user.CreateUser(input, r.Sql.Db)

	if err != nil {
		log.Error().Str("name", input.Username).Str("path", "CreateUser").Msg(err.Error())
		return nil, err
	}

	u := model.User{
		Username:              user.GetUserName(),
		PhoneNumber:           user.GetPhoneNumber(),
		AccountBalanceInCents: int(user.GetAccountBalanceInCents()),
		FaceEnrollmentStatus:  user.GetFaceEnrollmentStatus(),
		PinEnrollmentStatus:   user.GetPinStatus(),
	}

	return &u, nil
}

// VerifyUser is the resolver for the verifyUser field.
func (r *mutationResolver) VerifyUser(ctx context.Context, phoneNumber string, otp string) (*model.Authorization, error) {
	//Check the validity of the phone number
	if err := validate.ValidateKenyanPhoneNumber(phoneNumber); err != nil {
		return nil, err
	}

	//Check the validity of an OTP code
	if err := validate.ValidateOtp(otp); err != nil {
		return nil, err
	}
	if err := phoneutils.CheckOtp(phoneNumber, otp); err != nil {
		return nil, err
	}
	user, err := user.VerifyUser(phoneNumber, r.Sql.Db)

	if err != nil {
		log.Error().Str("phone_number", phoneNumber).Str("path", "VerifyUser").Msg(err.Error())
		return nil, err
	}

	credentials := jwt.TokenCredentials{
		Username: user.GetUserName(),
		Role:     "user",
	}
	token, err := jwt.GenerateToken(credentials)
	if err != nil {
		log.Error().Str("username", credentials.Username).Str("role", credentials.Role).Str("path", "VerifyUser").Msg(err.Error())
		return nil, err
	}
	log.Info().Str("username", credentials.Username).Str("role", credentials.Role).Str("path", "VerifyUser").Msg("user verified successfully!")

	return &model.Authorization{
		Token:                token,
		Role:                 model.RoleUser,
		PinEnrollmentStatus:  user.GetPinStatus(),
		FaceEnrollmentStatus: user.GetFaceEnrollmentStatus(),
	}, nil
}

// UserLogin is the resolver for the userLogin field.
func (r *mutationResolver) UserLogin(ctx context.Context, phoneNumber string, password string) (*model.Authorization, error) {
	// Find the user that matches the input phone number
	user, err := user.GetUserWithPhoneNumber(r.Sql.Db, phoneNumber)

	if err != nil {
		log.Info().Str("phone_number", phoneNumber).Str("path", "UserLogin").Msg(err.Error())
		return nil, err
	}
	//check if the password of the user matches the input password
	if err := encrypt.CheckPassword(user.GetPassword(), password); err != nil {
		log.Info().Str("path", "UserLogin").Msg(err.Error())
		return nil, err
	}

	credentials := jwt.TokenCredentials{
		Username: user.GetUserName(),
		Role:     "user",
	}
	token, err := jwt.GenerateToken(credentials)
	if err != nil {
		log.Error().Str("username", credentials.Username).Str("role", credentials.Role).Str("path", "UserLogin").Msg(err.Error())
		return nil, err
	}
	log.Info().Str("username", credentials.Username).Str("role", credentials.Role).Str("path", "UserLogin").Msg("user logged in successfully!")
	return &model.Authorization{
		Token:                token,
		Role:                 model.RoleUser,
		PinEnrollmentStatus:  user.GetPinStatus(),
		FaceEnrollmentStatus: user.GetFaceEnrollmentStatus(),
	}, nil
}

// ForgotUserPassword is the resolver for the forgotUserPassword field.
func (r *mutationResolver) ForgotUserPassword(ctx context.Context, phoneNumber string) (*model.SendCodeStatus, error) {
	//validate phone number
	if err := validate.ValidateKenyanPhoneNumber(phoneNumber); err != nil {
		return nil, err
	}

	//check if the phone number exists in the database
	phoneexists, err := user.CheckUserPhoneNumber(r.Sql.Db, phoneNumber)

	//return any error that might be associated with checking the phone number's existence in the database
	if err != nil {
		log.Error().Str("phone_number", phoneNumber).Str("path", "ForgotUserPassword").Msg(err.Error())
		return nil, err
	}
	//return an error if phone number does not exist in verified form
	if phoneexists.IsVerified == false {
		err1 := errors.New(errors.EARUserNotFoundByPhone, pgerror.New("phone number does not exist in verified form"))
		err1.Log()
		return nil, err1
	}
	//send an OTP code to the phone number provided, return error if there is any
	if err := phoneutils.SendOtp(phoneNumber); err != nil {
		log.Error().Str("phone_number", phoneNumber).Str("path", "ForgotUserPassword").Msg(err.Error())
		return nil, err
	}
	//return status on success
	sendcodestatus := &model.SendCodeStatus{
		PhoneNumber: phoneNumber,
		Success:     true,
	}
	return sendcodestatus, nil
}

// RequestUserPasswordReset is the resolver for the requestUserPasswordReset field.
func (r *mutationResolver) RequestUserPasswordReset(ctx context.Context, phoneNumber string, otp string) (*model.Authorization, error) {
	//Check the validity of an OTP code
	if err := phoneutils.CheckOtp(phoneNumber, otp); err != nil {
		return nil, err
	}

	user, err := user.GetUserWithPhoneNumber(r.Sql.Db, phoneNumber)

	if err != nil {
		log.Info().Str("phone_number", phoneNumber).Str("path", "RequestUserPasswordReset").Msg(err.Error())
		return nil, err
	}

	credentials := jwt.TokenCredentials{
		Username: user.GetUserName(),
		Role:     "user",
	}
	token, err := jwt.GenerateToken(credentials)
	if err != nil {
		log.Error().Str("username", credentials.Username).Str("role", credentials.Role).Str("path", "RequestUserPasswordReset").Msg(err.Error())
		return nil, err
	}
	return &model.Authorization{
		Token:                token,
		Role:                 model.RoleUser,
		PinEnrollmentStatus:  user.GetPinStatus(),
		FaceEnrollmentStatus: user.GetFaceEnrollmentStatus(),
	}, nil
}

// ResetUserPassword is the resolver for the resetUserPassword field.
func (r *mutationResolver) ResetUserPassword(ctx context.Context, newPassword string) (*model.User, error) {
	u, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}

	// Add this safety check to catch unauthenticated users
	if u == nil {
		err1 := errors.New(errors.EARUserUnauthenticated, pgerror.New("authentication required to reset user password"))
		err1.Log()
		return nil, err1
	}

	role := u.GetRole()
	if role != "user" {
		err1 := errors.New(errors.EARUserUnauthenticated, pgerror.New("access to reset user password denied"))
		err1.Log()
		return nil, err1
	}

	username := u.GetUsername()

	//validate inputs
	if err := validate.ValidatePassword(newPassword); err != nil {
		return nil, err
	}

	encryptedpassword, err := encrypt.HashPassword(newPassword)

	if err != nil {
		return nil, err
	}

	user, err := user.UpdatePassword(r.Sql.Db, encryptedpassword, username)
	if err != nil {
		log.Error().Str("username", username).Str("path", "ResetUserPassword").Msg(err.Error())
		return nil, err
	}

	user1 := model.User{
		Username:              user.GetUserName(),
		PhoneNumber:           user.GetPhoneNumber(),
		AccountBalanceInCents: int(user.GetAccountBalanceInCents()),
		FaceEnrollmentStatus:  user.GetFaceEnrollmentStatus(),
		PinEnrollmentStatus:   user.GetPinStatus(),
	}

	//return the updated record
	return &user1, nil
}

// UpdateUserPinCode is the resolver for the updateUserPinCode field.
func (r *mutationResolver) UpdateUserPinCode(ctx context.Context, newPincode string) (*model.User, error) {
	u, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}

	// Add this safety check to catch unauthenticated users
	if u == nil {
		err1 := errors.New(errors.EARUserUnauthenticated, pgerror.New("authentication required to update user pin code"))
		err1.Log()
		return nil, err1
	}

	role := u.GetRole()
	if role != "user" {
		err1 := errors.New(errors.EARUserUnauthenticated, pgerror.New("access to Update user PinCode denied"))
		err1.Log()
		return nil, err1
	}
	username := u.GetUsername()

	encryptedpincode, err := encrypt.HashPassword(newPincode)

	if err != nil {
		return nil, err
	}

	user2, err := user.UpdatePinCode(r.Sql.Db, encryptedpincode, username)
	if err != nil {
		log.Error().Str("username", username).Str("path", "UpdateUserPinCode").Msg(err.Error())
		return nil, err
	}

	user1 := model.User{
		Username:              user2.GetUserName(),
		PhoneNumber:           user2.GetPhoneNumber(),
		AccountBalanceInCents: int(user2.GetAccountBalanceInCents()),
		FaceEnrollmentStatus:  user2.GetFaceEnrollmentStatus(),
		PinEnrollmentStatus:   user2.GetPinStatus(),
	}

	//return the updated record
	return &user1, nil
}

// UpdateUserFacialEmbeddings is the resolver for the updateUserFacialEmbeddings field.
func (r *mutationResolver) UpdateUserFacialEmbeddings(ctx context.Context, newEmbeddings []string) (*model.User, error) {
	u, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}

	// Add this safety check to catch unauthenticated users
	if u == nil {
		err1 := errors.New(errors.EARUserUnauthenticated, pgerror.New("authentication required to update facial embeddings"))
		err1.Log()
		return nil, err1
	}

	role := u.GetRole()
	if role != "user" {
		err1 := errors.New(errors.EARUserUnauthenticated, pgerror.New("access to Update user facial embeddings denied"))
		err1.Log()
		return nil, err1
	}
	username := u.GetUsername()

	user2, err := user.UpdateFacialEmbeddings(r.Sql.Db, newEmbeddings, username)
	if err != nil {
		log.Error().Str("username", username).Str("path", "UpdateUserFacialEmbeddings").Msg(err.Error())
		return nil, err
	}

	user1 := model.User{
		Username:              user2.GetUserName(),
		PhoneNumber:           user2.GetPhoneNumber(),
		AccountBalanceInCents: int(user2.GetAccountBalanceInCents()),
		FaceEnrollmentStatus:  user2.GetFaceEnrollmentStatus(),
		PinEnrollmentStatus:   user2.GetPinStatus(),
	}

	//return the updated record
	return &user1, nil
}

// RegenerateUserQRCode is the resolver for the regenerateUserQrCode field.
func (r *mutationResolver) RegenerateUserQRCode(ctx context.Context) (*model.User, error) {
	u, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}

	// Add this safety check to catch unauthenticated users
	if u == nil {
		err1 := errors.New(errors.EARUserUnauthenticated, pgerror.New("authentication required to regenerate user qr code"))
		err1.Log()
		return nil, err1
	}

	role := u.GetRole()
	if role != "user" {
		err1 := errors.New(errors.EARUserUnauthenticated, pgerror.New("access to regenerate user qr code denied"))
		err1.Log()
		return nil, err1
	}
	username := u.GetUsername()

	user1, err := user.RegenerateQrCode(r.Sql.Db, username)
	if err != nil {
		return nil, err
	}

	qr := user1.GetQrCodeBase64()

	userprofile := model.User{
		Username:              user1.GetUserName(),
		PhoneNumber:           user1.GetPhoneNumber(),
		QRCode:                &qr,
		AccountBalanceInCents: int(user1.GetAccountBalanceInCents()),
		FaceEnrollmentStatus:  user1.GetFaceEnrollmentStatus(),
		PinEnrollmentStatus:   user1.GetPinStatus(),
	}
	return &userprofile, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context) (*model.User, error) {
	user1, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}

	// Add this safety check to catch unauthenticated users
	if user1 == nil {
		err1 := errors.New(errors.EARUserUnauthenticated, pgerror.New("authentication required to get user"))
		err1.Log()
		return nil, err1
	}

	role := user1.GetRole()
	if role != "user" {
		err1 := errors.New(errors.EARUserUnauthenticated, pgerror.New("access to get user profile denied"))
		err1.Log()
		return nil, err1
	}

	username := user1.GetUsername()

	u, err := user.GetUserWithUsername(r.Sql.Db, username)
	if err != nil {
		log.Error().Str("username", username).Str("path", "GetUser").Msg(err.Error())
		return nil, err
	}
	log.Info().Str("id", username).Str("role", role).Str("path", "GetUser").Msg("getting user's profile")

	qr := u.GetQrCodeBase64()
	userprofile := model.User{
		Username:              u.GetUserName(),
		PhoneNumber:           u.GetPhoneNumber(),
		QRCode:                &qr,
		AccountBalanceInCents: int(u.GetAccountBalanceInCents()),
		FaceEnrollmentStatus:  u.GetFaceEnrollmentStatus(),
		PinEnrollmentStatus:   u.GetPinStatus(),
	}
	return &userprofile, nil
}

// GetUserStateByUUID is the resolver for the getUserStateByUuid field.
func (r *queryResolver) GetUserStateByUUID(ctx context.Context, uuid []string) ([]*model.User, error) {
	s, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}
	if s == nil {
		err1 := errors.New(errors.EARMerchantUnauthenticated, pgerror.New("access to get offline user denied"))
		err1.Log()
		return nil, err1
	}
	role := s.GetRole()
	if role != "merchant" {
		err1 := errors.New(errors.EARMerchantUnauthenticated, pgerror.New("access to get offline user denied"))
		err1.Log()
		return nil, err1
	}

	//get user from database via uuids
	dbusers, err := user.GetUsersByUUIDs(r.Sql.Db, model.ParseUUIDSlice(uuid))
	if err != nil {
		return nil, err
	}

	if dbusers == nil {
		return nil, nil
	}

	Userslist := make([]*model.User, len(dbusers))

	for i, dbuser := range dbusers {

		uuidStr := dbuser.GetUUID()

		user := &model.User{
			Username:              dbuser.GetUserName(),
			PhoneNumber:           dbuser.GetPhoneNumber(),
			UUID:                  &uuidStr,
			FacialEmbeddings:      pointer.Get(dbuser.GetFacialEmbeddings()),
			AccountBalanceInCents: int(dbuser.GetAccountBalanceInCents()),
			FaceEnrollmentStatus:  dbuser.GetFaceEnrollmentStatus(),
			PinEnrollmentStatus:   dbuser.GetPinStatus(),
		}
		Userslist[i] = user
	}
	return Userslist, nil
}

// Transactions is the resolver for the transactions field.
func (r *userResolver) Transactions(ctx context.Context, obj *model.User, limit *int, offset *int, startTime *time.Time, endTime *time.Time) ([]*model.Transaction, error) {
	user1, err := auth.ForContext(ctx)
	if err != nil {
		return nil, err
	}
	// Add this safety check to catch unauthenticated users
	if user1 == nil {
		err1 := errors.New(errors.EARUserUnauthenticated, pgerror.New("authentication required to get user transactions"))
		err1.Log()
		return nil, err1
	}

	role := user1.GetRole()
	if role != "user" {
		err1 := errors.New(errors.EARUserUnauthenticated, pgerror.New("access to get user transactions denied"))
		err1.Log()
		return nil, err1
	}

	username := user1.GetUsername()

	transactions, err := transaction.GetTransactionsForUser(r.Sql.Db, username, limit, offset, startTime, endTime)

	if err != nil {
		return nil, err
	}

	// 4. Transform DB model to GraphQL model with pre-allocated slice
	transactionslist := make([]*model.Transaction, 0, len(transactions))

	for _, transaction := range transactions {
		t := &model.Transaction{
			TransactionID:          transaction.GetTransactionID(),
			CreatedAt:              transaction.GetCreatedAt(),
			UpdatedAt:              transaction.GetUpdatedAt(),
			TotalAmountInCents:     int(transaction.GetTotalAmountInCents()),
			TransactionCostInCents: int(transaction.GetTransactionCostInCents()),
			UserUsername:           transaction.GetUserName(),
			MerchantUsername:       transaction.GetMerchantName(),
		}
		transactionslist = append(transactionslist, t)
	}

	return transactionslist, nil
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
