#returns a user's data
type User {
  id: Int!
  createdAt: Time!
  updatedAt: Time!
  username: String!
  phone_number: String!
  mpesa_number: String
  qr_code: String!
  account_balance_in_cents: Int!
  transactions: [Transaction!]
}

#fields required for adding a new user to the system
input NewUser {
  username: String!
  phone_number: String!
  password: String!
  mpesa_number: String
}

extend type Query {
  getUser: User
  getUsers: [User!]
}

extend type Mutation {
  createUser(input: NewUser!): User!
  verifyUser(phone_number: String!, otp: String!): String
  userLogin(phone_number: String!, password: String!): String
  forgotUserPassword(phone_number: String!): SendCodeStatus!
  requestUserPasswordReset(phone_number: String!, otp: String!): String
  resetUserPassword(new_password: String!): User!
  updateUserPinCode(new_pincode: String!, otp: String!): User!
  regenerateUserQrCode: User!
}
