package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"

	"github.com/GigaDesk/eardrum-server/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// VerifyUser is the resolver for the verifyUser field.
func (r *mutationResolver) VerifyUser(ctx context.Context, phoneNumber string, otp string) (*string, error) {
	panic(fmt.Errorf("not implemented: VerifyUser - verifyUser"))
}

// UserLogin is the resolver for the userLogin field.
func (r *mutationResolver) UserLogin(ctx context.Context, phoneNumber string, password string) (*string, error) {
	panic(fmt.Errorf("not implemented: UserLogin - userLogin"))
}

// ForgotUserPassword is the resolver for the forgotUserPassword field.
func (r *mutationResolver) ForgotUserPassword(ctx context.Context, phoneNumber string) (*model.SendCodeStatus, error) {
	panic(fmt.Errorf("not implemented: ForgotUserPassword - forgotUserPassword"))
}

// RequestUserPasswordReset is the resolver for the requestUserPasswordReset field.
func (r *mutationResolver) RequestUserPasswordReset(ctx context.Context, phoneNumber string, otp string) (*string, error) {
	panic(fmt.Errorf("not implemented: RequestUserPasswordReset - requestUserPasswordReset"))
}

// ResetUserPassword is the resolver for the resetUserPassword field.
func (r *mutationResolver) ResetUserPassword(ctx context.Context, newPassword string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: ResetUserPassword - resetUserPassword"))
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUser - getUser"))
}

// GetUsers is the resolver for the getUsers field.
func (r *queryResolver) GetUsers(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUsers - getUsers"))
}

// Transactions is the resolver for the transactions field.
func (r *userResolver) Transactions(ctx context.Context, obj *model.User) ([]*model.Transaction, error) {
	panic(fmt.Errorf("not implemented: Transactions - transactions"))
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
