// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
)

// GetInputStruct returns struct filled from map obj defined by name
// Example useage struct validation with github.com/go-playground/validator by directive:
//
//	func ValidateDirective(ctx context.Context, obj interface{}, next graphql.Resolver) (res interface{}, err error) {
//	  field := graphql.GetPathContext(ctx)
//	  if data, ok := obj.(map[string]interface{}); ok {
//	    for _, v := range field.ParentField.Field.Arguments {
//	      name := v.Value.ExpectedType.Name()
//	      model, err := model.GetInputStruct(name, data)
//	      if err != nil {
//	        //handle not found error
//	      }
//	      if err := validate.Struct(model); err != nil {
//	      //handle error
//	      }
//	    }
//	  }
//	  return next(ctx)
//	}
func GetInputStruct(name string, obj map[string]interface{}) (interface{}, error) {
	switch name {
	}
	return nil, fmt.Errorf("%s not found", name)
}
