// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package db

import (
	"gorm.io/gorm"
)

type AutoGqlDB struct {
	Db    *gorm.DB
	Hooks map[string]any
}

// Create a new AutoGqlDB
func NewAutoGqlDB(db *gorm.DB) AutoGqlDB {
	return AutoGqlDB{
		Db:    db,
		Hooks: make(map[string]any),
	}
}
